#!/usr/bin/env node

var rewind = require('./'),
    concat = require('concat-stream'),
    fs = require('fs'),
    argv = require('minimist')(process.argv.slice(2), {
        boolean: 'counterclockwise'
    });

const help = `
usage:

    geojson-rewind < foo.geojson > foo.geojson
    geojson-rewind foo.geojson > bar.geojson

options:

    --counterclockwise

    if specified, set outer ring to counterclockwise
    and inner rings to clockwise`.trim();

if (process.stdin.isTTY && !argv._[0]) {
    console.log(help);
    process.exit(1);
}

(argv._.length ? fs.createReadStream(argv._[0]) : process.stdin).pipe(concat(convert));

function convert(data) {
    process.stdout.write(JSON.stringify(rewind(JSON.parse(data), argv.counterclockwise), argv));
}
